Sys.setlocale("LC_TIME", "English")
par(mar = c(4, 4, 1, 1), pty = "s", mfrow = c(2, 2))
hpc <- read.table(file = "household_power_consumption.txt", sep = ";", skip = 66637, nrows = 2880)
names <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
colnames(hpc) <- names
hpc$datetime <- strptime(paste(hpc$Date, hpc$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
with(hpc, {
  plot(datetime, Global_active_power, type = "l", ylab = "Global Active Power", xlab = "")
  plot(datetime, Voltage, type = "l", ylab = "Voltage", xlab = "datetime")
  with(hpc, plot(datetime, Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = ""))
  with(hpc, points(datetime, Sub_metering_2, type = "l", col = "red"))
  with(hpc, points(datetime, Sub_metering_3, type = "l", col = "blue"))
  legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n", cex = 0.6)
  plot(datetime, Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab = "datetime")
})
dev.copy(png, file = "plot4.png")
dev.off()